name: Compile C++ to EXE

on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]
workflow_dispatch:

jobs:
build:
runs-on: windows-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Setup MinGW C++ Compiler
    uses: egor-tisin/setup-mingw@v2
    with:
      version: 12.2.0

  - name: Compile C++ File
    run: |
      g++ main.cpp -o program.exe

  - name: Upload EXE File
    uses: actions/upload-artifact@v4
    with:
      name: Hasil-Program-EXE
      path: program.exe
